spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://db:3306/${DB_NAME}?useSSL=false&serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # 필요하다면 develop환경에서만 사용
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

server:
  port: 8050