spring:
  datasource:
    url: jdbc:mysql://db:3306/${DB_NAME}?useSSL=false&serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update    # 개발 환경에서만 사용
    show-sql: true        # 개발 환경에서만 사용
    properties:
      hibernate:
        format_sql: true  # SQL 포맷팅
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8050